### ISSUE TITLE
Publish 1.2.1 to npm?

### ISSUE THREAD

**Issue by paulirwin** [Availity/availity-uikit#141]
The version of [availity-uikit on the npmjs registry](https://www.npmjs.com/package/availity-uikit) is quite old at 0.7.2. Can someone publish the latest availity-uikit to npm?

**Comment by robmcguinness** [comment]
No problemo.  That version was actually published accidentally long back and is not NPM compatible.  We have a 2.x beta version available on npm:

```bash
npm install availity-uikit@next --save
```

Only reason 2.0 hasn't been released is because we are still testing and creating the changelog.

#### FYI

Shortly after we release 2.x we will release a [3.x version](https://github.com/Availity/availity-uikit/tree/feature/bootstrap-4) based on Bootstrap 4 that is designed to work with React.js + [Reactstrap](https://reactstrap.github.io/).  @TheSharpieOne is handling 3.x of availity-uikit.

Let me know if that helps.
