### ISSUE TITLE
Disabled Wizard Steps still respond to clicks.

### ISSUE THREAD

**Issue by IndifferentDisdain** [Availity/availity-uikit#146]
http://availity.github.io/availity-uikit/v3.0.0-beta.2/pages/components/#vertical click on step 4 (the disabled one), and you'll see the URL change. Will submit PR to address.

**Comment by TheSharpieOne** [comment]
At most, with CSS `pointer-events: none;` can be added. This is what bootstrap will add for `a.btn.disabled` to prevent the click from triggering the action. Using this only prevents clicks, keyboard navigation can still get to the elements and trigger it. Adding something like `tabindex="-1"` will make it so that keyboard users will not be able to tab to it.

So, the documentation markup needs to change to add the `tabindex` and the styles for `a.stepwizard-step.disabled` should include `pointer-events: none;`.

All version are affected by this (v1, v2, and v3)

**Comment by IndifferentDisdain** [comment]
I also noticed that when you set pointer-events: none, any cursor selection (in this case, cursor: not-allowed) is ignored. Not sure if that's a problem for you or not.

**Comment by IndifferentDisdain** [comment]
Considering the only js in this project as of now is for a modal, I didn't want to go down a js-specific fix for something as menial as this unless you want to.

**Comment by TheSharpieOne** [comment]
Yeah, pointer-events: none will prevent any interaction. All events (hover click and such) end up firing on the element behind it... That would prevent seeing the cursor change. Having a wrapper would solve the problem via css but would introduce additional markup. 
I would like to not have any javascript in this library. I am tempted to do what bootstrap did and tell the user about the problem and how to solve it in their code. This is because a JavaScript solution here may not work too well with the vast and various libraries out there.

**Comment by IndifferentDisdain** [comment]
+1. So, how about I just update the example to remove the href and place a comment in there?

**Comment by IndifferentDisdain** [comment]
Will update PR right now.

**Comment by TheSharpieOne** [comment]
Fixed via #147
